<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzx8nx5\installerProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzx8nx5/installerProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPzx8nx5.legacy');

    return;
}

if (!\class_exists(installerProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPzx8nx5\installerProdDebugProjectContainer::class, installerProdDebugProjectContainer::class, false);
}

return new \ContainerPzx8nx5\installerProdDebugProjectContainer(array(
    'container.build_hash' => 'Pzx8nx5',
    'container.build_id' => '98e4548d',
    'container.build_time' => 1533127759,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzx8nx5');
