<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCbwzvid\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCbwzvid/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCbwzvid.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCbwzvid\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCbwzvid\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Cbwzvid',
    'container.build_id' => 'ecc38880',
    'container.build_time' => 1533128602,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCbwzvid');
